### ISSUE TITLE
Adopt Contributor Covenant 2.0

### ISSUE THREAD

**Issue by arirawr** [EmbarkStudios/opensource-template#22]
Contributor Covenant has made updates since we adopted their CoC. We should take a look at version 2.0 and decide if we should update our CoC.

https://www.contributor-covenant.org/version/2/0/code_of_conduct/

cc @XAMPPRocky @lpil

**Comment by lpil** [comment]
Here's the changelog: https://github.com/ContributorCovenant/contributor_covenant/blob/release/changelog

> - Emphasizes 'community' over 'project' scope, effectively merging the Community Covenant into the Contributor Covenant
> - Adds expectation about accepting responsibility and apologizing to those affected by mistakes, and learning from the experience to the list
> - Adds sexual attention and advances of any kind as unacceptable behavior example
> - Moves enforcement responsibilities from project maintainers to community leaders
> - Adds responsibility to communicate reasons for moderation decisions when removing, editing, or rejecting contributions not aligned to the Code of Conduct
> - Requires community leaders to respect privacy and security of the reporter of any incident, not just confidentiality
> - Provides a template for code of conduct enforcement

I've not read 2.0 yet but I like the sound of these changes a lot.

**Comment by lpil** [comment]
2.0 reads well, I'd be in favour of adopting it.

I'm not sure where the "template for code of conduct enforcement" is. Is that the "Enforcement Guidelines" section?

**Comment by arirawr** [comment]
yes I think so, the levels of enforcement action they added.

**Comment by lpil** [comment]
cc @celialewis3

**Comment by celialewis3** [comment]
Looks great to me, super straightforward. In my experience, most people's go-to defense is "I didn't know if I did x that I would get y!" Hard for rule violators to argue with consequences that they already implicitly agree to by joining the community!

**Comment by repi** [comment]
Read through the new one, and looks great!

Maybe we could make it feature a bit more on https://embark.dev also in the bottom? Include the logo and name maybe (if one is allowed)?

**Comment by XAMPPRocky** [comment]
What's the action item(s) here? It seems there's consensus to adopt but what is actually required to consider adoption complete?

**Comment by lpil** [comment]
Update the CoC document and the badge in the READMEs, and perhaps share news of the update in Discord + Slack?

**Comment by XAMPPRocky** [comment]
okay, I've opened PRs for every repo (I think).

- [ ] [buildkite-jobify](https://github.com/EmbarkStudios/buildkite-jobify/pull/13)
- [ ] [superluminal-perf-rs](https://github.com/EmbarkStudios/superluminal-perf-rs/pull/6)
- [ ] [rpmalloc-rs](https://github.com/EmbarkStudios/rpmalloc-rs/pull/12)
- [ ] [nfd2](https://github.com/EmbarkStudios/nfd2/pull/16)
- [ ] [cfg-expr](https://github.com/EmbarkStudios/cfg-expr/pull/14)
- [ ] [rust-gpu](https://github.com/EmbarkStudios/rust-gpu/pull/271)
- [ ] [tryhard](https://github.com/EmbarkStudios/tryhard/pull/5)
- [ ] [physx-rs](https://github.com/EmbarkStudios/physx-rs/pull/106)
- [ ] [tame-gcs](https://github.com/EmbarkStudios/tame-gcs/pull/37)
- [ ] [texture-synthesis](https://github.com/EmbarkStudios/texture-synthesis/pull/155)
- [ ] [puffin](https://github.com/EmbarkStudios/puffin/pull/11)
- [ ] [ash-molten](https://github.com/EmbarkStudios/ash-molten/pull/37)
- [ ] [cargo-about](https://github.com/EmbarkStudios/cargo-about/pull/138)
- [ ] [cargo-deny](https://github.com/EmbarkStudios/cargo-deny/pull/307)
- [ ] [tame-oauth](https://github.com/EmbarkStudios/tame-oauth/pull/25)
- [ ] [spdx](https://github.com/EmbarkStudios/spdx/pull/28)
- [ ] [krates](https://github.com/EmbarkStudios/krates/pull/23)
- [ ] [cargo-fetcher](https://github.com/EmbarkStudios/cargo-fetcher/pull/147)


For others how I did this was with a small script with the `gh` cli client.
```bash
#!/usr/bin/env bash

set -e

CURRENT_DIR=$(pwd)

mkdir -p ./repos
cd ./repos
# Iterate over each repo provided.
for repo in "$@"
do
    git clone git@github.com:EmbarkStudios/$repo.git
    cd $repo
    git checkout -b update-coc
    sed -i "" s/v1.4%20adopted/v2.0%20adopted/ README.md
    cat $CURRENT_DIR/coc.md > CODE_OF_CONDUCT.md
    git add .
    git commit -m "Update Code Of Covenant to 2.0"
    git push -u origin update-coc
    gh pr create --fill
done
```

**Comment by repi** [comment]
Ah neat with the script!

Can one give review approval via the CLI also?

**Comment by khyperia** [comment]
Ah, right, saw this in `rust-gpu` before I found this issue, should fix https://github.com/EmbarkStudios/rust-gpu/pull/271#pullrequestreview-537501950 before mass-merging

**Comment by XAMPPRocky** [comment]
> Can one give review approval via the CLI also?

Yep, with `gh pr review --approve`

**Comment by Jake-Shadle** [comment]
Was confused why tame-gcs's tests started failing then realized I was using the code of conduct as test content because it "never" changes. :sweat_smile:

**Comment by XAMPPRocky** [comment]
> Hey everyone, we've updated our Code Of Conduct for open source projects to the latest version of the Contributor Covenant (2.0). We've already updated most of repositories with the new text. If you haven't read it already you check it out on the contributor covenant website. https://www.contributor-covenant.org/version/2/0/code_of_conduct/

Draft of the announcement to post on Discord and slack. If it looks good I'll post it later today.

**Comment by lpil** [comment]
Sounds good! Thanks @XAMPPRocky

**Comment by arirawr** [comment]
Thanks for taking this as @XAMPPRocky ! That message looks good to me.

**Comment by XAMPPRocky** [comment]
Posted on Discord and Slack, so I think we can close as complete. There's only couple of repos still open (`rpmalloc-rs` and `ash-molten` specifically) one of which can be merged, and the other is blocked on unrelated build failures which we can track in their specific PRs.
